<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultation Report - {{ $consultation->topic }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        .header {
            border-bottom: 3px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
        }
        .info-section {
            margin-bottom: 30px;
        }
        .info-row {
            display: flex;
            margin-bottom: 10px;
        }
        .info-label {
            font-weight: bold;
            width: 150px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 10px;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 5px;
        }
        .section-content {
            line-height: 1.6;
            white-space: pre-wrap;
        }
        .rating {
            font-size: 24px;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
        }
        @media print {
            body { margin: 0; padding: 15px; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Consultation Report</h1>
        <p style="color: #6b7280; margin: 5px 0;">BizConsult Platform</p>
    </div>

    <div class="info-section">
        <div class="info-row">
            <div class="info-label">Topic:</div>
            <div>{{ $consultation->topic }}</div>
        </div>
        <div class="info-row">
            <div class="info-label">Client:</div>
            <div>{{ $consultation->customer->name ?? 'Unknown' }}</div>
        </div>
        <div class="info-row">
            <div class="info-label">Consultant:</div>
            <div>{{ optional(optional($consultation->consultantProfile)->user)->name ?? 'Unknown' }}</div>
        </div>
        @if($consultation->scheduled_date)
        <div class="info-row">
            <div class="info-label">Consultation Date:</div>
            <div>
                {{ \Carbon\Carbon::parse($consultation->scheduled_date)->format('M j, Y') }}
                @if($consultation->scheduled_time)
                    at {{ \Carbon\Carbon::parse($consultation->scheduled_time)->format('g:i A') }}
                @endif
            </div>
        </div>
        @endif
        <div class="info-row">
            <div class="info-label">Report Generated:</div>
            <div>{{ now()->format('M j, Y g:i A') }}</div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Consultation Summary</div>
        <div class="section-content">{{ $consultation->consultation_summary }}</div>
    </div>

    <div class="section">
        <div class="section-title">Recommendations</div>
        <div class="section-content">{{ $consultation->recommendations }}</div>
    </div>

    <div class="section">
        <div class="section-title">Client Readiness Rating</div>
        <div>
            @php
                $rating = $consultation->client_readiness_rating ?? 0;
                $emoji = $rating === 1 ? '😟' : ($rating === 2 ? '😐' : ($rating === 3 ? '🙂' : ($rating === 4 ? '😊' : '🤩')));
            @endphp
            <span class="rating">{{ $emoji }} {{ $rating }}/5</span>
            <p style="margin-top: 5px; color: #6b7280;">
                @if($rating <= 2)
                    Client needs more preparation before implementing recommendations.
                @elseif($rating == 3)
                    Client is moderately ready to proceed.
                @else
                    Client is well-prepared to implement the recommendations.
                @endif
            </p>
        </div>
    </div>

    @if($consultation->details)
    <div class="section">
        <div class="section-title">Additional Details</div>
        <div class="section-content">{{ $consultation->details }}</div>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated by BizConsult Platform</p>
        <p>© {{ date('Y') }} BizConsult. All rights reserved.</p>
    </div>

    <div class="no-print" style="margin-top: 30px; text-align: center;">
        <button onclick="window.print()" style="background: #2563eb; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
            Print / Save as PDF
        </button>
    </div>
</body>
</html>

